import type { Partner } from "./types";

/** Demo partners — replace with API aggregation when backend supports location/currency fields. */
export const MOCK_PARTNERS: Partner[] = [
  {
    id: "partner-altek",
    name: "Altek International FZE",
    activeTOS: "Standard LSKB Export",
    pricingRecords: [
      {
        id: "altek-mombasa-fob",
        incoterm: "FOB",
        location: "Mombasa",
        costCurrency: "USD",
        costAmount: 1180,
        priceCurrency: "KES",
        priceAmount: 168500,
      },
      {
        id: "altek-mombasa-cfr",
        incoterm: "CFR",
        location: "Mombasa",
        costCurrency: "USD",
        costAmount: 1245,
        priceCurrency: "KES",
        priceAmount: 175200,
      },
      {
        id: "altek-addis-dap",
        incoterm: "DAP",
        location: "Addis Ababa",
        costCurrency: "USD",
        costAmount: 1320,
        priceCurrency: "ETB",
        priceAmount: 78500,
      },
      {
        id: "altek-addis-fca",
        incoterm: "FCA",
        location: "Addis Ababa",
        costCurrency: "USD",
        costAmount: 1290,
        priceCurrency: "ETB",
        priceAmount: 76200,
      },
    ],
  },
  {
    id: "partner-sika",
    name: "Sika Abyssinia Chemicals PLC",
    activeTOS: "Import Contract A",
    pricingRecords: [
      {
        id: "sika-nairobi-fob",
        incoterm: "FOB",
        location: "Nairobi",
        costCurrency: "USD",
        costAmount: 980,
        priceCurrency: "KES",
        priceAmount: 142000,
      },
      {
        id: "sika-nairobi-cif",
        incoterm: "CIF",
        location: "Nairobi",
        costCurrency: "USD",
        costAmount: 1045,
        priceCurrency: "KES",
        priceAmount: 149800,
      },
      {
        id: "sika-mombasa-fca",
        incoterm: "FCA",
        location: "Mombasa",
        costCurrency: "USD",
        costAmount: 1010,
        priceCurrency: "USD",
        priceAmount: 1185,
      },
      {
        id: "sika-addis-dap",
        incoterm: "DAP",
        location: "Addis Ababa",
        costCurrency: "USD",
        costAmount: 1150,
        priceCurrency: "ETB",
        priceAmount: 69200,
      },
    ],
  },
  {
    id: "partner-basf",
    name: "BASF East Africa Ltd",
    activeTOS: "Regional Distribution TOS 2026",
    pricingRecords: [
      {
        id: "basf-mombasa-fob",
        incoterm: "FOB",
        location: "Mombasa",
        costCurrency: "USD",
        costAmount: 890,
        priceCurrency: "KES",
        priceAmount: 131500,
      },
      {
        id: "basf-addis-fca",
        incoterm: "FCA",
        location: "Addis Ababa",
        costCurrency: "EUR",
        costAmount: 820,
        priceCurrency: "ETB",
        priceAmount: 54800,
      },
      {
        id: "basf-nairobi-exw",
        incoterm: "EXW",
        location: "Nairobi",
        costCurrency: "USD",
        costAmount: 760,
        priceCurrency: "KES",
        priceAmount: 118900,
      },
    ],
  },
  {
    id: "partner-huntsman",
    name: "Huntsman Polyurethanes",
    activeTOS: "Direct Import Framework",
    pricingRecords: [
      {
        id: "huntsman-mombasa-cfr",
        incoterm: "CFR",
        location: "Mombasa",
        costCurrency: "USD",
        costAmount: 1420,
        priceCurrency: "USD",
        priceAmount: 1595,
      },
      {
        id: "huntsman-addis-dap",
        incoterm: "DAP",
        location: "Addis Ababa",
        costCurrency: "USD",
        costAmount: 1510,
        priceCurrency: "ETB",
        priceAmount: 91200,
      },
    ],
  },
];
