import type { CRMPartner, PMSProduct, PricingRecord } from "./types";

export const MOCK_CRM_PARTNERS: CRMPartner[] = [
  { id: "crm-altek", name: "Altek International FZE", type: "buyer" },
  { id: "crm-sika", name: "Sika Abyssinia Chemicals PLC", type: "buyer" },
  { id: "crm-basf", name: "BASF East Africa Ltd", type: "buyer" },
  { id: "crm-huntsman", name: "Huntsman Polyurethanes", type: "supplier" },
  { id: "crm-dhl", name: "DHL Global Forwarding", type: "logistics" },
];

export const MOCK_PMS_PRODUCTS: PMSProduct[] = [
  { id: "pms-lskb-001", sku: "LSKB-001", name: "LeanChem Sodium Bicarbonate FG" },
  { id: "pms-lskb-002", sku: "LSKB-002", name: "LeanChem Sodium Bicarbonate Tech" },
  { id: "pms-caustic-010", sku: "CAOH-010", name: "Caustic Soda Flakes 98%" },
  { id: "pms-h2o2-020", sku: "H2O2-020", name: "Hydrogen Peroxide 50%" },
  { id: "pms-poly-030", sku: "PU-030", name: "Polyurethane Resin Blend" },
];

const FX_USD_KES = 129.5;
const FX_USD_ETB = 130;

/** Active + historical pricing rows linked to CRM partners and PMS products. */
export const MOCK_PRICING_RECORDS: PricingRecord[] = [
  {
    id: "pr-altek-lskb-fob-hist",
    crmPartnerId: "crm-altek",
    pmsProductId: "pms-lskb-001",
    incoterm: "FOB",
    location: "Mombasa",
    costCurrency: "USD",
    costAmount: 1150,
    priceCurrency: "KES",
    priceAmount: 162000,
    exchangeRateUsed: FX_USD_KES,
    baseCurrency: "KES",
    validFrom: "2025-06-01",
    validTo: "2026-04-30",
    status: "historical",
  },
  {
    id: "pr-altek-lskb-fob-active",
    crmPartnerId: "crm-altek",
    pmsProductId: "pms-lskb-001",
    incoterm: "FOB",
    location: "Mombasa",
    costCurrency: "USD",
    costAmount: 1180,
    priceCurrency: "KES",
    priceAmount: 168500,
    exchangeRateUsed: FX_USD_KES,
    baseCurrency: "KES",
    validFrom: "2026-05-01",
    validTo: null,
    status: "active",
  },
  {
    id: "pr-altek-lskb-cfr-active",
    crmPartnerId: "crm-altek",
    pmsProductId: "pms-lskb-001",
    incoterm: "CFR",
    location: "Mombasa",
    costCurrency: "USD",
    costAmount: 1245,
    priceCurrency: "KES",
    priceAmount: 175200,
    exchangeRateUsed: FX_USD_KES,
    baseCurrency: "KES",
    validFrom: "2026-05-01",
    validTo: null,
    status: "active",
  },
  {
    id: "pr-altek-caustic-dap-active",
    crmPartnerId: "crm-altek",
    pmsProductId: "pms-caustic-010",
    incoterm: "DAP",
    location: "Addis Ababa",
    costCurrency: "USD",
    costAmount: 1320,
    priceCurrency: "ETB",
    priceAmount: 78500,
    exchangeRateUsed: FX_USD_ETB,
    baseCurrency: "ETB",
    validFrom: "2026-03-15",
    validTo: null,
    status: "active",
  },
  {
    id: "pr-sika-lskb-fob-hist",
    crmPartnerId: "crm-sika",
    pmsProductId: "pms-lskb-002",
    incoterm: "FOB",
    location: "Nairobi",
    costCurrency: "USD",
    costAmount: 950,
    priceCurrency: "KES",
    priceAmount: 138000,
    exchangeRateUsed: FX_USD_KES,
    baseCurrency: "KES",
    validFrom: "2025-08-01",
    validTo: "2026-04-30",
    status: "historical",
  },
  {
    id: "pr-sika-lskb-fob-active",
    crmPartnerId: "crm-sika",
    pmsProductId: "pms-lskb-002",
    incoterm: "FOB",
    location: "Nairobi",
    costCurrency: "USD",
    costAmount: 980,
    priceCurrency: "KES",
    priceAmount: 142000,
    exchangeRateUsed: FX_USD_KES,
    baseCurrency: "KES",
    validFrom: "2026-05-01",
    validTo: null,
    status: "active",
  },
  {
    id: "pr-sika-h2o2-fca-active",
    crmPartnerId: "crm-sika",
    pmsProductId: "pms-h2o2-020",
    incoterm: "FCA",
    location: "Mombasa",
    costCurrency: "USD",
    costAmount: 1010,
    priceCurrency: "USD",
    priceAmount: 1185,
    exchangeRateUsed: null,
    baseCurrency: "USD",
    validFrom: "2026-02-01",
    validTo: null,
    status: "active",
  },
  {
    id: "pr-basf-lskb-fob-active",
    crmPartnerId: "crm-basf",
    pmsProductId: "pms-lskb-001",
    incoterm: "FOB",
    location: "Mombasa",
    costCurrency: "USD",
    costAmount: 890,
    priceCurrency: "KES",
    priceAmount: 131500,
    exchangeRateUsed: FX_USD_KES,
    baseCurrency: "KES",
    validFrom: "2026-04-01",
    validTo: null,
    status: "active",
  },
  {
    id: "pr-basf-poly-exw-hist",
    crmPartnerId: "crm-basf",
    pmsProductId: "pms-poly-030",
    incoterm: "EXW",
    location: "Nairobi",
    costCurrency: "USD",
    costAmount: 720,
    priceCurrency: "KES",
    priceAmount: 112000,
    exchangeRateUsed: FX_USD_KES,
    baseCurrency: "KES",
    validFrom: "2025-01-01",
    validTo: "2026-04-30",
    status: "historical",
  },
  {
    id: "pr-basf-poly-exw-active",
    crmPartnerId: "crm-basf",
    pmsProductId: "pms-poly-030",
    incoterm: "EXW",
    location: "Nairobi",
    costCurrency: "USD",
    costAmount: 760,
    priceCurrency: "KES",
    priceAmount: 118900,
    exchangeRateUsed: FX_USD_KES,
    baseCurrency: "KES",
    validFrom: "2026-05-01",
    validTo: null,
    status: "active",
  },
  {
    id: "pr-huntsman-poly-cfr-active",
    crmPartnerId: "crm-huntsman",
    pmsProductId: "pms-poly-030",
    incoterm: "CFR",
    location: "Mombasa",
    costCurrency: "USD",
    costAmount: 1420,
    priceCurrency: "USD",
    priceAmount: 1595,
    exchangeRateUsed: null,
    baseCurrency: "USD",
    validFrom: "2026-01-15",
    validTo: null,
    status: "active",
  },
  {
    id: "pr-huntsman-caustic-dap-active",
    crmPartnerId: "crm-huntsman",
    pmsProductId: "pms-caustic-010",
    incoterm: "DAP",
    location: "Addis Ababa",
    costCurrency: "USD",
    costAmount: 1510,
    priceCurrency: "ETB",
    priceAmount: 91200,
    exchangeRateUsed: FX_USD_ETB,
    baseCurrency: "ETB",
    validFrom: "2026-03-01",
    validTo: null,
    status: "active",
  },
];
