-- LeanChem curated / recommended products (manual list, separate from Chemical_Master_Data).
-- Run once in Supabase SQL editor. Table starts empty.

CREATE TABLE IF NOT EXISTS public."LeanChem_Recommended_Products" (
  "Row_No" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Sector" text,
  "Supplier_Name" text,
  "Category" text,
  "Sub_Category" text,
  "Product_Name" text NOT NULL,
  "Generic_Name" text,
  "Product_Type" text,
  "Packaging" text,
  "HS_Code" text,
  "Country_of_Origin" text,
  source_master_row_no bigint,
  recommendation_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS lean_chem_recommended_products_name_idx
  ON public."LeanChem_Recommended_Products" ("Product_Name");

CREATE INDEX IF NOT EXISTS lean_chem_recommended_products_source_idx
  ON public."LeanChem_Recommended_Products" (source_master_row_no)
  WHERE source_master_row_no IS NOT NULL;

COMMENT ON TABLE public."LeanChem_Recommended_Products" IS
  'LeanChem suggested/recommended products — curated manually; may link to Chemical_Master_Data via source_master_row_no.';
