/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogisticsIntercompanyTransferRouteImport } from './routes/logistics.intercompany-transfer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIntercompanyTransferRoute =
  LogisticsIntercompanyTransferRouteImport.update({
    id: '/logistics/intercompany-transfer',
    path: '/logistics/intercompany-transfer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logistics/intercompany-transfer': typeof LogisticsIntercompanyTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logistics/intercompany-transfer': typeof LogisticsIntercompanyTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logistics/intercompany-transfer': typeof LogisticsIntercompanyTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logistics/intercompany-transfer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logistics/intercompany-transfer'
  id: '__root__' | '/' | '/logistics/intercompany-transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogisticsIntercompanyTransferRoute: typeof LogisticsIntercompanyTransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/intercompany-transfer': {
      id: '/logistics/intercompany-transfer'
      path: '/logistics/intercompany-transfer'
      fullPath: '/logistics/intercompany-transfer'
      preLoaderRoute: typeof LogisticsIntercompanyTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogisticsIntercompanyTransferRoute: LogisticsIntercompanyTransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
