/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogisticsStockMovementsRouteImport } from './routes/logistics.stock-movements'
import { Route as LogisticsStockAvailabilityRouteImport } from './routes/logistics.stock-availability'
import { Route as LogisticsIntercompanyTransferRouteImport } from './routes/logistics.intercompany-transfer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsStockMovementsRoute = LogisticsStockMovementsRouteImport.update({
  id: '/logistics/stock-movements',
  path: '/logistics/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsStockAvailabilityRoute =
  LogisticsStockAvailabilityRouteImport.update({
    id: '/logistics/stock-availability',
    path: '/logistics/stock-availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticsIntercompanyTransferRoute =
  LogisticsIntercompanyTransferRouteImport.update({
    id: '/logistics/intercompany-transfer',
    path: '/logistics/intercompany-transfer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logistics/intercompany-transfer': typeof LogisticsIntercompanyTransferRoute
  '/logistics/stock-availability': typeof LogisticsStockAvailabilityRoute
  '/logistics/stock-movements': typeof LogisticsStockMovementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logistics/intercompany-transfer': typeof LogisticsIntercompanyTransferRoute
  '/logistics/stock-availability': typeof LogisticsStockAvailabilityRoute
  '/logistics/stock-movements': typeof LogisticsStockMovementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logistics/intercompany-transfer': typeof LogisticsIntercompanyTransferRoute
  '/logistics/stock-availability': typeof LogisticsStockAvailabilityRoute
  '/logistics/stock-movements': typeof LogisticsStockMovementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logistics/intercompany-transfer'
    | '/logistics/stock-availability'
    | '/logistics/stock-movements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logistics/intercompany-transfer'
    | '/logistics/stock-availability'
    | '/logistics/stock-movements'
  id:
    | '__root__'
    | '/'
    | '/logistics/intercompany-transfer'
    | '/logistics/stock-availability'
    | '/logistics/stock-movements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogisticsIntercompanyTransferRoute: typeof LogisticsIntercompanyTransferRoute
  LogisticsStockAvailabilityRoute: typeof LogisticsStockAvailabilityRoute
  LogisticsStockMovementsRoute: typeof LogisticsStockMovementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/stock-movements': {
      id: '/logistics/stock-movements'
      path: '/logistics/stock-movements'
      fullPath: '/logistics/stock-movements'
      preLoaderRoute: typeof LogisticsStockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/stock-availability': {
      id: '/logistics/stock-availability'
      path: '/logistics/stock-availability'
      fullPath: '/logistics/stock-availability'
      preLoaderRoute: typeof LogisticsStockAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/intercompany-transfer': {
      id: '/logistics/intercompany-transfer'
      path: '/logistics/intercompany-transfer'
      fullPath: '/logistics/intercompany-transfer'
      preLoaderRoute: typeof LogisticsIntercompanyTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogisticsIntercompanyTransferRoute: LogisticsIntercompanyTransferRoute,
  LogisticsStockAvailabilityRoute: LogisticsStockAvailabilityRoute,
  LogisticsStockMovementsRoute: LogisticsStockMovementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
